### PR TITLE
Fix screen stacking bug

### LINKED ISSUE #665: Don't allow Create Torrent window to open from Prefs window
Currently, you can alternate clicking Create New Torrent and Preferences to create a stack of prefs and new torrent windows as deep as you want, and move between them using the back and forward buttons.

### PR DESCRIPTION
**Pull request by dcposch**
You can no longer open a whole stack of Prefs windows, or Create Torrent windows

Simplifies and fixes behavior when dropping files onto the app or the dock icon. Before, you could use drag-drop to create stacks of Create Torrent windows. Now, you can only create torrents from the home screen.

Fixes #665

### CODE REVIEW

**Comment by dcposch** [comment]
@feross

File: src/main/menu.js [hunk 1]
```diff
@@ -350,6 +333,17 @@ function getMenuTemplate () {
       click: () => dialog.openSeedFile()
     })
 
+    // Edit -> Preferencs (Windows, Linux)
```
Comment (feross) [inline src/main/menu.js]: Preferences

File: src/main/menu.js [hunk 2]
```diff
@@ -24,26 +23,28 @@ function init () {
...
+function setWindowFocus (flag) {
+  getMenuItem('Full Screen').enabled = flag
+  getMenuItem('Float on Top').enabled = flag
+}
+
+// Disallow opening more screens on top of the current one.
+function setAllowNav (flag) {
+  getMenuItem('Preferences').enabled = flag
+  getMenuItem('Create New Torrent...').enabled = flag
+  getMenuItem('Open Torrent File...').enabled = flag
```
Comment (feross) [inline src/main/menu.js]: You're missing the "Create New Torrent from File..." option. This one only appears on Windows/Linux, so you'll need an if-statement to check that it exists before setting the `enabled` property.

File: src/main/menu.js (hunk 1 above)
Comment (feross) [inline src/main/menu.js]: This comment should be "Edit menu (Windows, Linux)" to match the style of the others.

File: src/renderer/controllers/torrent-list-controller.js [hunk 3]
```diff
@@ -40,6 +40,11 @@ module.exports = class TorrentListController {
 
   // Shows the Create Torrent page with options to seed a given file or folder
   showCreateTorrent (files) {
+    // You can only create torrents from the home screen.
+    if (this.state.location.url() !== 'home') {
+      return dispatch('error', 'Please go back to the torrent list before creating a new torrent.')
```
Comment (feross) [inline src/renderer/controllers/torrent-list-controller.js]: It's not ideal that this error appears in two places. Can't it be removed from here? With the changes in this PR, it's not possible for the drag-and-drop handler to call `showCreateTorrent` except from the home screen anyway.

Comment (feross) [inline src/renderer/controllers/torrent-list-controller.js]: The one other place I think it can be called is via the menu item "Create New Torrent..." when the player is open. Shouldn't the player also do `ipcRenderer.send('setAllowNav', false)`? This seems like the right place to handle it. Then this line can be removed here.

**Comment by feross** [comment]
LGTM -- but see inline comments.

File: src/main/menu.js [hunk 4]
```diff
@@ -24,26 +23,28 @@ function init () {
...
-  getMenuItem('Add Subtitles File...').enabled = true
+function setWindowFocus (flag) {
+  getMenuItem('Full Screen').enabled = flag
+  getMenuItem('Float on Top').enabled = flag
+}
+
+// Disallow opening more screens on top of the current one.
+function setAllowNav (flag) {
+  getMenuItem('Preferences').enabled = flag
+  getMenuItem('Create New Torrent...').enabled = flag
```
Comment (feross) [inline src/main/menu.js]: You're missing the "Create New Torrent from File..." option. This one only appears on Windows/Linux, so you'll need an if-statement to check that it exists before setting the `enabled` property.

File: src/main/menu.js [hunk 5]
```diff
@@ -24,26 +23,28 @@ function init () {
...
+  getMenuItem('Open Torrent File...').enabled = flag
+  getMenuItem('Open Torrent Address...').enabled = flag
```
Comment (feross) [inline src/main/menu.js]: These last two "Open..." options don't actually navigate to new pages. They're equivalent to drag-and-dropping a new .torrent file onto the app (which is supported from all pages). For that reason, shouldn't these options remain enabled?

**Comment by feross** [comment]
Nice work! This is a lot more consistent. I like it.

LGTM -- but see inline comments.

File: src/renderer/controllers/torrent-list-controller.js (hunk 3 above)
Comment (dcposch) [inline src/renderer/controllers/torrent-list-controller.js]: > Shouldn't the player also do ipcRenderer.send('setAllowNav', false)? 

Then you can't open Prefs from within the player

Comment (feross) [inline src/renderer/controllers/torrent-list-controller.js]: Oh, that's bad. Okay, this is fine then.

Btw right now, you also can't open Prefs from within the Create Torrent page.

File: src/main/menu.js (hunk 4 above)
Comment (dcposch) [inline src/main/menu.js]: Good call, added

File: src/main/menu.js (hunk 5 above)
Comment (dcposch) [inline src/main/menu.js]: Sure, I'll put them back

File: src/renderer/controllers/torrent-list-controller.js (hunk 3 above)
Comment (dcposch) [inline src/renderer/controllers/torrent-list-controller.js]: Just tried it --- I *can* open Prefs from within Create Torrent. (I just can't open another Prefs from within Prefs, or another Create Torrent from within either of those.)

File: src/main/menu.js (hunk 1 above)
Comment (dcposch) [inline src/main/menu.js]: fixed

**Comment by feross** [comment]
👍

**Comment by feross** [comment]
Released in WebTorrent Desktop v0.11!
